// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdwp_ZV0FdGPX65NcNb5NVDVFc13wF3SA',
    appId: '1:89206376966:web:d371786445f27f282c1187',
    messagingSenderId: '89206376966',
    projectId: 'phone-calling-f4763',
    authDomain: 'phone-calling-f4763.firebaseapp.com',
    storageBucket: 'phone-calling-f4763.firebasestorage.app',
    measurementId: 'G-KCVN07J03J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldx8H3sfK9r3rROEW-I0GmerAEAEvo98',
    appId: '1:89206376966:android:c500ac17e0f0d96d2c1187',
    messagingSenderId: '89206376966',
    projectId: 'phone-calling-f4763',
    storageBucket: 'phone-calling-f4763.firebasestorage.app',
  );
}
